services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./Backend/.env.example
    restart: always
    networks:
      - edustream-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - edustream-network

  web:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/app
      - ./Backend/dist/media:/app/dist/media
      - ./Backend/dist/static:/app/dist/static
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env.example
    depends_on:
      - db
      - redis
    networks:
      - edustream-network

  frontend:
    build:
      context: ./Frontend/dist
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web
    networks:
      - edustream-network

volumes:
  postgres_data:

networks:
  edustream-network:
    driver: bridge




